const initialState = {
  allWorlds: null,
  allDatacenters: [
    'Aether',
    'Chaos',
    'Crystal',
    'Elemental',
    'Gaia',
    'Light',
    'Mana',
    'Primal',
  ],
  authChecked: false,
  scoutData: {},
  routeData: {
    Lakeland: [],
    Kholusia: [],
    'Amh Araeng': [],
    'Il Mheg': [],
    "The Rak'tika Greatwood": [],
    'The Tempest': []
  },
  markCoords: [],
  error: false,
  totalStops: 0,
  cardError: false,
  cardNotification: null,
  currentStop: 0,
  currentMark: {
    mark: ' - ',
    zone: ' - ',
    coords: ' - ',
    instance: ' - '
  },
  cardKey: '',
  radioChecked: false,
  datacenter: '',
  dataCenterURL: null,
  discord: false,
  formNotification: null,
  formError: false,
  formSuccess: false,
  formLogin: true,
  formCreate: false,
  formServer: 'default',
  guideData: null,
  guideIndex: 0,
  isLoading: false,
  markCount: 0,
  modalType: null,
  scoutedZoneKeys: [],
  shared: false,
  showModal: false,
  showNav: false,
  showLocation: false,
  uiConfig: null,
  userData: null,
  text: '',
  world: '',
  zoneKeys: null,
  zoneData: null
};

export default initialState;
